### ISSUE TITLE
Any advantages over actions/cache?

### ISSUE THREAD

**Issue by andreasabel** [action-works/cabal-cache#2]
I came by this repo looking for sound and robust ways to cache dependencies for builds with `cabal`.
Looking at the README, it was not clear to me what makes this action stand out over the standard action `actions/cache`.
Also, development work seems to mostly have ceased on this repo.

So, is there a preferred use of this action vs. `action/cache`?  
If there is such a killer app, maybe it should be explained in the README.

**Comment by newhoggy** [comment]
This action is obsolete.  Users should use https://github.com/action-works/cabal-cache-s3 instead.

The advantage of using https://github.com/action-works/cabal-cache-s3 is that it supports fine grained cache, so a failed build, if it built anything will be able to cache any packages that built.  A fine grained cache also means that sharing is maximised between builds.
