### ISSUE TITLE
[Action needed by 31st May 2023] The `save-state` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by mberlanda** [action-works/cabal-cache#3]
Following the [README instructions](https://github.com/action-works/cabal-cache/blob/main/examples.md#haskell---cabal), I just added cabal-cache to one of my packages (https://github.com/mberlanda/exercism-hs/pull/5).

```
      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}

```

During the first execution, the step logs contained:

```
Warning: The `save-state` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files.
For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Cache not found for input keys: Linux-
```

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

> We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. 

I suspect that the warning will affect this repository as well given this snippet https://github.com/action-works/cabal-cache/blob/71c6614ec9d7414e0e5c8fb33f7de801a76afc03/src/restore.ts#L77-L79 `

**Comment by newhoggy** [comment]
Thank you for your report.  This action is obsolete and users should use https://github.com/action-works/cabal-cache-s3 instead.
